# Travis CI credentials

language: scala

services:
    - mysql

scala:
 - "2.10.4"

# Emails to notify
notifications:
  slack:
    rooms:
      - websudos:P9QNXx1ZGFnDHp3v3jUqtB8k

  email:
  - dev@newzly.com

# Branches to build.
branches:
  only:
    - master
    - develop

jdk:
  - oraclejdk7
  - openjdk7

script: "./scripts/run_tests.sh"

