# Travis CI credentials

language: scala

services:
    - mysql

cache:
  directories:
   - $HOME/.ivy2/cache
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
sudo: false
scala:
- 2.10.5
- 2.11.7
env:
  global:
  - GH_REF: github.com/outworkers/morpheus.git
  - secure: WwLG0fkVV1DS5P6GeLOHjPJ2z+GP9UaLzX27DuHBEXRxNPPw27y7jag0gbbf6E80kYwGB4zfBx9YjcJFVFdGCCcAjDJHMP8kLQirUak1jzuoWZFUEtTkF7ev/OVs0PmMHrOGuysT4W/UaL9MZD/mYO5lO9oavycTQ0kbOwZJwUg=
  - secure: Qtr5ULJ90s5pfLBaXRKFLMPBcDSYBQfUVz+abgjlG/um8iWE/OJswYn2n3zylAqnI4bSKhPobl6bBYzt8f6k9kzMqpR4t/4gWFV1LJUas0eAsTnrjV1He4nbPvO9RVEkvuQcTCqmus2AgYEnwdKhGWwktok5PAoJ22ycy4HK8C8=
  - secure: hbuc+lReAC/tzOfmF3M70L4Qfb48S6fI/gqchctnBD7TcZ6i13EOLhsjgPkFwTuINYU7Bvwd54yjy9simu1Se34+DaGtxKPJ8NZIeWk0ciCGyFxNiz0QVkE+/Cc0kZLD7hJXb0UpLsbMwpIQFlL6FHcB/2xGmMhgYvGHe7+64zM=
notifications:
  slack:
  - websudos:P9QNXx1ZGFnDHp3v3jUqtB8k
  email:
  - dev@websudos.co.uk
branches:
  only:
  - master
  - develop
jdk:
- oraclejdk7
- oraclejdk8
before_script:
  - travis_retry sbt ++$TRAVIS_SCALA_VERSION update
  - mysql -e "CREATE DATABASE morpheus_test;"
  - mysql -e "CREATE USER 'morpheus'@'localhost' IDENTIFIED BY 'morpheus23!';"
  - mysql -e "SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('morpheus23!')"
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coverageAggregate
  coveralls
after_success:
- ./build/publish_develop.sh
