# Travis CI credentials

language: scala

services:
    - mysql

scala:
 - "2.10.4"

# Emails to notify
notifications:
  slack:
    rooms:
      - websudos:P9QNXx1ZGFnDHp3v3jUqtB8k

  email:
  - dev@websudos.com

# Branches to build.
branches:
  only:
    - master
    - develop

sudo: false

jdk:
  - oraclejdk7
  - openjdk7


before_script:
  - mysql -e 'create database morpheus;'

script: "sbt clean coverage test"

